"""rename nombre to nombre_docu in documento

Revision ID: 01a1f6dab107
Revises: adf565d79cd0
Create Date: 2026-08-10 15:34:55.002126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '01a1f6dab107'
down_revision: Union[str, Sequence[str], None] = 'adf565d79cd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documento', sa.Column('nombre_docu', sa.String(length=255), nullable=False))
    op.drop_column('documento', 'nombre')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documento', sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('documento', 'nombre_docu')
    # ### end Alembic commands ###
