"""Add terminos banco y cuenta to proveedor

Revision ID: 19e068bc2ce9
Revises: f94949fe936f
Create Date: 2026-09-03 13:45:24.429432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e068bc2ce9'
down_revision: Union[str, Sequence[str], None] = 'f94949fe936f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proveedor', sa.Column('terminos', sa.Text(), nullable=True))
    op.add_column('proveedor', sa.Column('banco', sa.String(length=100), nullable=True))
    op.add_column('proveedor', sa.Column('cuenta', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proveedor', 'cuenta')
    op.drop_column('proveedor', 'banco')
    op.drop_column('proveedor', 'terminos')
    # ### end Alembic commands ###
