"""agregar fecha_recibido y fecha_entregado a devoluciones

Revision ID: 2bdc3d6e0e3f
Revises: d1627996b28f
Create Date: 2026-08-20 11:10:28.600311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bdc3d6e0e3f'
down_revision: Union[str, Sequence[str], None] = 'd1627996b28f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devoluciones', sa.Column('fecha_recibido', sa.Date(), nullable=True))
    op.add_column('devoluciones', sa.Column('fecha_entregado', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devoluciones', 'fecha_entregado')
    op.drop_column('devoluciones', 'fecha_recibido')
    # ### end Alembic commands ###
