"""add registro_sanitario and estado to producto

Revision ID: 31ec1709c3a3
Revises: 
Create Date: 2026-08-10 13:04:48.124924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ec1709c3a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('registro_sanitario', sa.String(), nullable=True))
    op.add_column('producto', sa.Column('estado', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
def upgrade() -> None:
    op.add_column('producto', sa.Column('registro_sanitario', sa.String(255), nullable=True))
    op.add_column('producto', sa.Column('estado', sa.String(255), nullable=True))
    # ### end Alembic commands ###
