"""crear tabla auditorias

Revision ID: 3bf478e04a9c
Revises: 19e068bc2ce9
Create Date: 2026-09-03 15:13:42.372437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf478e04a9c'
down_revision: Union[str, Sequence[str], None] = '19e068bc2ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_auditor', sa.String(length=100), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('documento_adt', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fecha_auditoria', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditorias_id'), 'auditorias', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditorias_id'), table_name='auditorias')
    op.drop_table('auditorias')
    # ### end Alembic commands ###
