"""renombrar fecha_cumpleanos a fecha_cumpleanios

Revision ID: 5471d7b076d3
Revises: a9d10d11fd4c
Create Date: 2026-08-21 09:07:58.643834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5471d7b076d3'
down_revision: Union[str, Sequence[str], None] = 'a9d10d11fd4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacto', sa.Column('fecha_cumpleanios', sa.Date(), nullable=True))
    op.drop_column('contacto', 'fecha_cumpleanos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacto', sa.Column('fecha_cumpleanos', sa.DATE(), nullable=True))
    op.drop_column('contacto', 'fecha_cumpleanios')
    # ### end Alembic commands ###
