"""add auditoria_tareas table and update auditorias fields

Revision ID: 8d35935d68db
Revises: 3bf478e04a9c
Create Date: 2026-09-04 09:53:34.287933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8d35935d68db'
down_revision: Union[str, Sequence[str], None] = '3bf478e04a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria_tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auditoria_id', sa.Integer(), nullable=False),
    sa.Column('nombre_tarea', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_ejecutada', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_tareas_id'), 'auditoria_tareas', ['id'], unique=False)
    op.add_column('auditorias', sa.Column('nombre_auditoria', sa.String(length=150), nullable=False))
    op.add_column('auditorias', sa.Column('fecha_programada', sa.DateTime(), nullable=False))
    op.add_column('auditorias', sa.Column('fecha_ejecucion', sa.DateTime(), nullable=True))
    op.add_column('auditorias', sa.Column('fecha_finalizada', sa.DateTime(), nullable=True))
    op.add_column('auditorias', sa.Column('novedades', sa.Text(), nullable=True))
    op.drop_column('auditorias', 'fecha_auditoria')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auditorias', sa.Column('fecha_auditoria', mysql.DATETIME(), nullable=False))
    op.drop_column('auditorias', 'novedades')
    op.drop_column('auditorias', 'fecha_finalizada')
    op.drop_column('auditorias', 'fecha_ejecucion')
    op.drop_column('auditorias', 'fecha_programada')
    op.drop_column('auditorias', 'nombre_auditoria')
    op.drop_index(op.f('ix_auditoria_tareas_id'), table_name='auditoria_tareas')
    op.drop_table('auditoria_tareas')
    # ### end Alembic commands ###
