"""agregar campo fecha_cumpleanos a contacto

Revision ID: a9d10d11fd4c
Revises: 2bdc3d6e0e3f
Create Date: 2026-08-21 09:03:58.922779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9d10d11fd4c'
down_revision: Union[str, Sequence[str], None] = '2bdc3d6e0e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacto', sa.Column('fecha_cumpleanos', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacto', 'fecha_cumpleanos')
    # ### end Alembic commands ###
