"""permite_proveedor_id_null_en_contacto

Revision ID: a9f13233e86d
Revises: 5471d7b076d3
Create Date: 2026-08-24 11:19:04.657585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a9f13233e86d'
down_revision: Union[str, Sequence[str], None] = '5471d7b076d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacto', 'proveedor_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('contacto_ibfk_1'), 'contacto', type_='foreignkey')
    op.create_foreign_key(None, 'contacto', 'proveedor', ['proveedor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacto', type_='foreignkey')
    op.create_foreign_key(op.f('contacto_ibfk_1'), 'contacto', 'proveedor', ['proveedor_id'], ['id'])
    op.alter_column('contacto', 'proveedor_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
