"""create tabla documento

Revision ID: adf565d79cd0
Revises: 31ec1709c3a3
Create Date: 2026-08-10 13:57:12.274073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf565d79cd0'
down_revision: Union[str, Sequence[str], None] = '31ec1709c3a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documento',
    sa.Column('id', sa.Integer(), nullable=False, primary_size=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('etiquetas', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documento_id'), 'documento', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documento_id'), table_name='documento')
    op.drop_table('documento')
    # ### end Alembic commands ###
