"""agregar_campo_activo_a_proveedor

Revision ID: c61f443a92d4
Revises: a9f13233e86d
Create Date: 2026-08-24 11:52:54.821916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c61f443a92d4'
down_revision: Union[str, Sequence[str], None] = 'a9f13233e86d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proveedor', sa.Column('activo', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proveedor', 'activo')
    # ### end Alembic commands ###
