"""add_registro_estado_to_producto

Revision ID: f94949fe936f
Revises: c61f443a92d4
Create Date: 2026-09-01 10:36:24.852699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94949fe936f'
down_revision: Union[str, Sequence[str], None] = 'c61f443a92d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'producto',
        sa.Column(
            'registro_estado',
            sa.String(length=20),
            nullable=False,
            server_default='activo'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto', 'registro_estado')
    # ### end Alembic commands ###
